env: dev
storage:
    database:
        directory: /var/databases
    session:
        lifetime: +7days
twig:
    debug: true
    cache: false
    template.directory: /template
routes:
    index:
        path: /
        controller: 'App\Controller\Main::index'
    register:
        path: /register
        controller: 'Kzu\Controller\Authentification::register'
    login:
        path: /login
        controller: 'Kzu\Controller\Authentification::login'
    logout:
        path: /logout
        controller: 'Kzu\Controller\Authentification::logout'
    admin:
        path: /admin
        controller: 'Kzu\Controller\Admin::index'
    admin_config:
        path: '/admin/config/{config}'
        controller: 'Kzu\Controller\Admin::config'
    admin_database:
        path: '/admin/database/{database}'
        controller: 'Kzu\Controller\Admin::database'
    assets_css:
        path: /assets/css
        controller: 'Kzu\Controller\Assets::css'
    assets_js:
        path: /assets/js
        controller: 'Kzu\Controller\Assets::js'
    error_404:
        path: /error/404
        controller: 'Kzu\Controller\Error::error_404'
assets:
    css:
        - bootstrap/css/bootstrap.css
        - bootstrap/css/bootstrap.css
        - fontawesome/css/all.min.css
        - flash/flash.css
        - css/app.css
    js:
        - bootstrap/js/bootstrap.bundle.min.js
        - js/jquery.min.js
        - flash/flash.js
        - js/app.js
        - js/authentification.js
